name: PressorGauge
channels:
- conda-forge
dependencies:
- python=3.8
- conda
- pandas
- matplotlib
- seaborn
- numpy
- scipy
- joblib
- scikit-learn
- psycopg2
- sqlalchemy
- progressbar2
- pip
- pip:
  - streamlit
